### ISSUE TITLE
Unable to mount E01 files on MacOS 10.14.2 installation

### ISSUE THREAD

**Issue by simsong** [libyal/libewf-legacy#3] opened 2019-01-12 18:27 UTC
I just downloaded the legacy libewf from this website, built it, and tried to mount a disk image:

```
[nimi ~/gits/libewf-20140608 13:23:02]$ sudo /usr/local/bin/ewfmount -X volicon=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns  /Volumes/SanDisk\ Extreme/tracy-home-2012-07-16-final.E01 /mnt/
ewfmount 20140608

[nimi ~/gits/libewf-20140608 13:24:08]$ df
Filesystem         1K-blocks       Used  Available Capacity iused               ifree %iused  Mounted on
/dev/disk1s1       976797816  954522992   14176600    99% 2254745 9223372036852521062    0%   /
devfs                    243        243          0   100%     842                   0  100%   /dev
/dev/disk1s4       976797816    7343084   14176600    35%       6 9223372036854775801    0%   /private/var/vm
map -hosts                 0          0          0   100%       0                   0  100%   /net
map auto_home              0          0          0   100%       0                   0  100%   /home
/dev/disk12s1      976557016  122210720  854143908    13%    2230 9223372036854773577    0%   /Volumes/SanDisk Extreme
ewfmount@osxfuse0          0          0          0   100%       0                   0  100%   /mnt
[nimi ~/gits/libewf-20140608 13:24:09]$ ls -l /mnt/
ls: /mnt/: No such file or directory
[nimi ~/gits/libewf-20140608 13:24:11]$ 
```

I am not sure what to do at this point.

**Comment by joachimmetz** [comment] 2019-01-12 19:08
I'm unable to reproduce this on 10.14.2

```
./libewf-20140804/ewftools/ewfmount -X volicon=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns image.E01 fuse/
ewfmount 20140804

ls -1 fuse/
ewf1

hexdump -C fuse/ewf1 | head -n 16
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400  10 00 00 00 64 00 00 00  05 00 00 00 4b 00 00 00  |....d.......K...|
00000410  01 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00  |................|
00000420  00 20 00 00 00 20 00 00  10 00 00 00 00 00 00 00  |. ... ..........|
00000430  c4 ac bf 4f 01 00 18 00  53 ef 01 00 01 00 00 00  |...O....S.......|
00000440  86 ab bf 4f 00 4e ed 00  00 00 00 00 01 00 00 00  |...O.N..........|
00000450  00 00 00 00 0b 00 00 00  80 00 00 00 38 00 00 00  |............8...|
00000460  02 00 00 00 01 00 00 00  f1 f8 da b8 57 ef 49 db  |............W.I.|
00000470  9c f5 b4 09 57 07 36 ed  00 00 00 00 00 00 00 00  |....W.6.........|
00000480  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000004e0  00 00 00 00 00 00 00 00  00 00 00 00 c5 83 92 cc  |................|
000004f0  d3 d0 44 99 ae fa 0c 51  d3 55 ff ce 01 00 00 00  |..D....Q.U......|
00000500  00 00 00 00 00 00 00 00  86 ab bf 4f 00 00 00 00  |...........O....|
00000510  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

Can you attach a config.log to this issue?
Can you try another mount point? instead of `/mnt/` a local sub directory?

```
ewfmount 20140804

mount_osxfuse: /mnt: Permission denied
Unable to create fuse channel.
```

**Comment by simsong** [comment] 2019-01-12 19:14
I have been able to access the volume. Apparently, the `ewf1` volume can only be accessed as root, not as the normal user, even though the directory `/mnt` is mode 655. Observe:

```
[nimi ~ 14:13:31]$ whoami
simsong
[nimi ~ 14:13:32]$ ls -l /mnt
ls: /mnt: No such file or directory
[nimi ~ 14:13:34]$ sudo bash
.bashrc
[nimi ~ 14:13:37]# whoami
root
[nimi ~ 14:13:39]# ls -l /mnt
total 18202560
-r--r--r--  1 root  wheel  18639421440 Jan 12 14:13 ewf1
[nimi ~ 14:13:42]# ls -lgd /mnt
drwxr-xr-x@ 2 wheel  0 Dec 31  1969 /mnt/
[nimi ~ 14:13:46]$ 
```

**Comment by joachimmetz** [comment] 2019-01-12 19:19
Likely one of the fuse options can alter that behavior. Also see: https://github.com/osxfuse/osxfuse/wiki/Mount-options

**Comment by joachimmetz** [comment] 2019-01-12 19:20
Closing this issue this seems to be WAI

**Closed by joachimmetz** 2019-01-12 19:20 UTC
